language: python
python:
  - '3.5'
  - '3.6'
install: pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database landavailability_test;' -U postgres
- cd landavailability
env:
  global:
  - DATABASE_URL=postgres://postgres@localhost:5432/landavailability_test
  - SECRET_KEY=abcd1234
  - OPBEAT_ORGANIZATION_ID=abcd1234
  - OPBEAT_APP_ID=abcd1234
  - OPBEAT_SECRET_TOKEN=abcd1234
  - OPBEAT_DISABLE_SEND=true
script: pytest -v --cov-report= --cov=voa tests/
after_success:
  - codecov
deploy:
  provider: heroku
  api_key:
    secure: "wXTPbE0uU6nD0nSVnLOpX6HOJqXQNbxxkb6rLh8s8CwcUNiuBwYu0YmOpgmDGu/AI0n5TMEiM15b1TZ5EkbHpi8bTG84j3Rc7ynux39COouG4Jeukt5OQmBYBMVgvvD4y0SH4cQQ1/5aZWp5AkculL4innPfyw9caT/lwLz2YGltoE0imzUA4SRcxIWH/O5vFmA4Y0ERMPwX594a7fdLOkZ8FeOCFQHmh9H/inG0riNGbjtkKCY7O2xy6ntDH4zZI3oTerQyh29eo9XIuZnSrvFsa2SARcLYfwKD1MxneJi2k0QsEcIfKcBjcbT1VXPJ7B1v63e4sz2RK7ttK8wK25vynv6akpRmFWhiNZAkVTUX+b3AWqq6p5b/aixWPPTjvcoKyx6oXH3XNXafSmfr3kWLDGx3AV9HuLEs5ahko0g6uO/qU60wTtOWZ+qJVm9UDuqDuyMl1641UqGe6jtVUmcfkftWXuLnf6HqiC+yCO46mcwXiATLWY0kP8qlzR/lzsGXXmlK07dl5zEyTZQOPF/CQQW3ni4MfD/qQOPUSnadN8k345TmE6mt+giXjZS4Ot83IDehe90yYOraYttQVmVF1xSVF+NEyVSH04iO9pN98UxxylISiUYYk8vO0qG767wQC57VNlQk1Xj2C7UL/wKEeDzxeuXiYL4Bre0eyUo="
  strategy: git
  app: land-availability-voa
  on:
    repo: alphagov/land-availability-voa
  run:
    - "python landavailability/manage.py migrate"
