# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_reference', models.CharField(blank=True, max_length=32, null=True)),
                ('uarn', models.CharField(max_length=100, unique=True)),
                ('ba_code', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_or_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_street_1', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_street_3', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_district', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_description', models.CharField(blank=True, max_length=255, null=True)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('adopted_rv', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('list_year', models.IntegerField(null=True)),
                ('ba_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ba_reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vo_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.CharField(blank=True, max_length=255, null=True)),
                ('to_date', models.CharField(blank=True, max_length=255, null=True)),
                ('scat_code_only', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=255, null=True)),
                ('unadjusted_price', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voa.Property'),
        ),
    ]
