# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voa', '0002_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_oa_description', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='adjustement_total',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='adjustement_total_before',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
