# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voa', '0005_auto_20170211_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='additional_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additionals', to='voa.Property'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='adjustment_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='voa.Property'),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='voa.Property'),
        ),
    ]
