# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voa', '0006_auto_20170211_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ba_reference_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
